on: push

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install and run Jest
      run: |
        cd frontend
        npm i
        npm test

  cypress:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Run Cypress
      uses: cypress-io/github-action@v2
      with:
        start: npm start
        working-directory: frontend

  heroku:
    runs-on: ubuntu-latest

    needs: [jest, cypress]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build static assets
      run: |
        cd frontend
        npm i
        npm build
    - uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "careers-in-code-frontend"
        email: "nathan@de1ux.com"
        dockerfile_directory: ./frontend
        process_type: web
