on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install and run Jest
      run: |
        cd frontend
        npm i
        npm test

    - name: Run Cypress
      working-directory: frontend
      uses: cypress-io/github-action@v2
      with:
        start: npm start