on: push

defaults:
  run:
    working-directory: ./frontend

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install and run Jest
      run: |
        npm i
        npm test

  cypress:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Run Cypress
      uses: cypress-io/github-action@v2
      with:
        start: npm start

  heroku:
    runs-on: ubuntu-latest

    needs: [jest, cypress]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "careers-in-code-frontend"
        heroku_email: "nathan@de1ux.com"
        appdir: "frontend"
        usedocker: true
